### ISSUE TITLE
Practica Text Box - Solano Mendoza Taoli

### ISSUE THREAD

**Issue by garaudy12** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-garaudy12#2]
[Practica Text Box - Solano Mendoza Taoli.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-garaudy12/files/6333127/Practica.Text.Box.-.Solano.Mendoza.Taoli.pdf)

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 18.4/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
